# Copyright MediaZ Teknoloji A.S. All Rights Reserved.
macro(nos_find_sdk version out_nos_plugin_sdk out_nos_subsystem_sdk out_sdk_dir)
	# Search for that specific version. If not found, warn the user about using the latest compatible version.
	list(FIND NOS_VERSIONS ${version} version_index)

	if(version_index EQUAL -1)
		message(WARNING "Nodos version ${version} not found. Using the latest compatible version.")
		set(max_compatible_version -1)

		foreach(index RANGE 1 ${NOS_SDK_END_RANGE})
			list(GET NOS_VERSIONS ${index} nos_version)
			string(REPLACE "." ";" nos_version_components ${nos_version})
			list(GET nos_version_components 0 major)
			list(GET nos_version_components 1 minor)

			if(major EQUAL version)
				if(minor GREATER max_compatible_version)
					set(max_compatible_version ${NOS_MINOR})
					set(version_index ${index})
				endif()
			endif()
		endforeach()

		if(index EQUAL -1)
			message(FATAL_ERROR "No compatible version found.")
		else()
			list(GET NOS_VERSIONS ${version_index} nos_version)
			list(GET NOS_SDK_DIRS ${version_index} nos_sdk_dir)
			set(${out_sdk_dir} ${nos_sdk_dir})
			string(REPLACE "." "_" version_target_suffix ${nos_version})
			set(${out_nos_plugin_sdk} nosPluginSDK_${version_target_suffix})
			set(${out_nos_subsystem_sdk} nosSubsystemSDK_${version_target_suffix})
		endif()
	endif()

	message(STATUS "Using Nodos version ${version}")
	list(GET NOS_VERSIONS ${version_index} nos_version)
	list(GET NOS_SDK_DIRS ${version_index} nos_sdk_dir)
	set(${out_sdk_dir} ${nos_sdk_dir})
	string(REPLACE "." "_" version_target_suffix ${nos_version})
	set(${out_nos_plugin_sdk} nosPluginSDK_${version_target_suffix})
	set(${out_nos_subsystem_sdk} nosSubsystemSDK_${version_target_suffix})
endmacro()