# Copyright MediaZ Teknoloji A.S. All Rights Reserved.
macro(nos_find_sdk requested_version out_nos_plugin_sdk out_nos_subsystem_sdk out_sdk_dir)
    # Search for the requested version
    list(FIND NOS_VERSIONS ${requested_version} found_version_idx)

    if(found_version_idx EQUAL -1)
        # Requested version not found, find the latest compatible version
        set(max_compatible_minor -1)
        set(max_compatible_patch -1)

        string(REPLACE "." ";" req_ver_components ${requested_version})
        list(GET req_ver_components 0 req_major)
        list(GET req_ver_components 1 req_minor)
        list(GET req_ver_components 2 req_patch)

        # First, look for the exact requested minor version
        foreach(index RANGE 1 ${NOS_SDK_END_RANGE})
            list(GET NOS_VERSIONS ${index} found_version)
            string(REPLACE "." ";" nos_version_components ${found_version})
            list(GET nos_version_components 0 major)
            list(GET nos_version_components 1 minor)
            list(GET nos_version_components 2 patch)

            if(major EQUAL req_major AND minor EQUAL req_minor)
                if(patch GREATER_EQUAL req_patch)
                    set(max_compatible_minor ${minor})
                    set(max_compatible_patch ${patch})
                    set(found_version_idx ${index})
                    break()
                endif()
            endif()
        endforeach()

        # If the exact minor version is not found, look for the latest compatible minor version
        if(found_version_idx EQUAL -1)
            foreach(index RANGE 1 ${NOS_SDK_END_RANGE})
                list(GET NOS_VERSIONS ${index} found_version)
                string(REPLACE "." ";" nos_version_components ${found_version})
                list(GET nos_version_components 0 major)
                list(GET nos_version_components 1 minor)
                list(GET nos_version_components 2 patch)

                if(major EQUAL req_major)
                    if(minor GREATER max_compatible_minor OR (minor EQUAL req_minor AND patch GREATER_EQUAL req_patch))
                        set(max_compatible_minor ${minor})
                        set(max_compatible_patch ${patch})
                        set(found_version_idx ${index})
                    endif()
                endif()
            endforeach()
        endif()

        if(found_version_idx EQUAL -1)
            message(FATAL_ERROR "No compatible version found.")
        else()
            list(GET NOS_VERSIONS ${found_version_idx} found_version)
            list(GET NOS_SDK_DIRS ${found_version_idx} nos_sdk_dir)
            set(${out_sdk_dir} ${nos_sdk_dir})
            string(REPLACE "." "_" version_target_suffix ${found_version})
            set(${out_nos_plugin_sdk} nosPluginSDK_${version_target_suffix})
            set(${out_nos_subsystem_sdk} nosSubsystemSDK_${version_target_suffix})
        endif()
    endif()

    list(GET NOS_VERSIONS ${found_version_idx} found_version)
    list(GET NOS_SDK_DIRS ${found_version_idx} nos_sdk_dir)
    message(STATUS "Using Nodos version ${found_version}")
    set(${out_sdk_dir} ${nos_sdk_dir})
    string(REPLACE "." "_" version_target_suffix ${found_version})
    set(${out_nos_plugin_sdk} nosPluginSDK_${version_target_suffix})
    set(${out_nos_subsystem_sdk} nosSubsystemSDK_${version_target_suffix})
endmacro()