pub mod init;
pub mod remote;
pub mod install;
mod info;
mod remove;
mod rescan;
mod deinit;
pub mod create;
mod sdk_info;
mod list;
mod publish;
mod publish_batch;
pub mod get;
pub mod sample;
mod unpublish;
mod pin;
mod node;
mod dev;
pub(crate) mod launch;
mod extension;
mod depend;
pub mod test;

use std::io;

use clap::{Arg, ArgAction, ArgMatches};
use thiserror::Error;
use crate::nosman::constants;
use crate::nosman::workspace::Workspace;

#[derive(Error, Debug)]
pub enum CommandError {
    #[error("I/O (file {}): {}", file, message)]
    IO { file: String, message: String },
    #[error("Invalid argument: {}", message)]
    InvalidArgument { message: String },
    #[error("Zip: {}", message)]
    Zip { message: String },
    #[error("{}", message)]
    Runtime { message: String },
}

impl From<io::Error> for CommandError {
    fn from(err: io::Error) -> Self {
        CommandError::IO { file: "Unknown".to_string(), message: format!("{}", err) }
    }
}

pub(crate) type CommandResult = Result<(), CommandError>;

pub trait Command {
    fn matched_args<'a, 'b>(&self, workspace: &'a Workspace, args : &'b ArgMatches) -> Option<&'b ArgMatches>;
    fn run(&self, workspace: &mut Workspace, command_name: Option<&str>, args: &ArgMatches) -> CommandResult;
    fn needs_workspace(&self) -> bool {
        true
    }
}

pub fn commands() -> Vec<Box<dyn Command>> {
    vec![
        Box::new(init::InitCommand {}),
        Box::new(remote::RemoteAddCommand {}),
        Box::new(remote::RemoteListCommand {}),
        Box::new(install::InstallCommand {}),
        Box::new(info::InfoCommand {}),
        Box::new(remove::RemoveCommand {}),
        Box::new(rescan::RescanCommand {}),
        Box::new(deinit::DeinitCommand {}),
        Box::new(create::CreateCommand {}),
        Box::new(sdk_info::SdkInfoCommand {}),
        Box::new(list::ListCommand {}),
        Box::new(publish::PublishCommand {}),
        Box::new(publish_batch::PublishBatchCommand {}),
        Box::new(get::GetCommand {}),
        Box::new(sample::SampleCommand {}),
        Box::new(unpublish::UnpublishCommand {}),
        Box::new(pin::PinCommand {}),
        Box::new(node::NodeCommand {}),
        Box::new(dev::DevPullCommand {}),
        Box::new(dev::DevGenCommand {}),
        Box::new(dev::DevStatusCommand {}),
        Box::new(dev::DevBuildCommand {}),
        Box::new(launch::LaunchCommand {}),
        Box::new(extension::Extension {}),
        Box::new(depend::DependsCommands{}),
        Box::new(test::TestCommand {}),
    ]
}

pub fn register_cli(app: clap::Command) -> clap::Command {

    let lang_tool_arg = Arg::new("language/tool")
        .long("language-tool")
        .short('l')
        .help("Language and tool to use")
        .value_parser(clap::builder::PossibleValuesParser::new(["cpp/cmake"]))
        .default_value("cpp/cmake");
    
    let version_check_arg = Arg::new("version_check")
        .long("version-check")
        .help("Check the version of the package against the index, to fail or continue with the release.")
        .value_parser(clap::builder::PossibleValuesParser::new(constants::POSSIBLE_VERSION_CHECK_STRATEGY))
        .default_value("strict")
        .required(false);
    
    let git_dir_arg = Arg::new("dir")
        .long("directory")
        .short('m')
        .help("Path to the directory to scan for git repositories")
        .action(ArgAction::Append)
        .num_args(1)
        .default_values(&[".", "Engine", "Module"]);

    app.subcommand(clap::Command::new("init")
        .about("Initialize a directory as a Nodos workspace.")
        .arg(Arg::new("allow_nested")
            .action(ArgAction::SetTrue)
            .long("allow-nested")
            .help("Allow creating a workspace even if the folder is already inside another workspace. This also allows to recreate an existing workspace.")
            .num_args(0)
            .required(false)
        )
    )
        .subcommand(clap::Command::new("deinit")
            .about("Deinitialize a Nodos workspace.")
        )
        .subcommand(clap::Command::new("install")
            .about("Install a module")
            .arg(Arg::new("module").required(true))
            .arg(Arg::new("version").required(false))
            .arg(Arg::new("exact")
                .action(ArgAction::SetTrue)
                .help("If not set, version parameter will be interpreted as minimum required version within that minor/patch version.\n\
            If no version 'x' such that 'a.b <= x < a.(b+1)' is found among installed modules, latest such version will be installed.\n\
            If version is set to 'latest' or has no minor component, it will fail.")
                .long("exact")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("without_deps")
                .long("without-deps")
                .help("Do not install dependencies of the module")
                .action(ArgAction::SetTrue)
            )
            .arg(Arg::new("prefix")
                .help("Folder path relative to out_dir. The module contents will be under this folder. By default, its '<module_name>-<version>'.")
                .long("prefix")
                .required(false)
            )
            .arg(Arg::new("out_dir")
                .help("The directory where the module will be installed")
                .default_value("./Module/Downloaded")
                .long("out-dir")
                .required(false)
            )
        )
        .subcommand(clap::Command::new("remove")
            .about("Remove a module")
            .arg(Arg::new("module").required(true))
            .arg(Arg::new("version").required(true))
        )
        .subcommand(clap::Command::new("rescan")
            .about("Rescan modules and update caches")
            .arg(Arg::new("fetch_index")
                .action(ArgAction::SetTrue)
                .help("Fetch remote module indices before scanning")
                .long("fetch-index")
                .num_args(0)
                .required(false)
            )
        )
        .subcommand(clap::Command::new("list")
            .about("List packages")
            .arg(Arg::new("installed")
                .action(ArgAction::SetTrue)
                .help("List installed modules")
                .long("installed")
                .num_args(0)
                .required(false)
                .group("list_type")
            )
            .arg(Arg::new("remote")
                .action(ArgAction::SetTrue)
                .help("List remote packages")
                .long("remote")
                .num_args(0)
                .required(false)
                .group("list_type")
            )
            .arg(Arg::new("package_name")
                .help("Name of the package to list remote/installed packages of")
                .long("package-name")
                .short('p')
                .required(false)
            )
        )
        .subcommand(clap::Command::new("info")
            .about("Returns information about an installed module in JSON format.\n\
        If no such module is installed, it will return an error.")
            .arg(Arg::new("module").required(true))
            .arg(Arg::new("version").required(true))
            .arg(Arg::new("relaxed")
                .action(ArgAction::SetTrue)
                .help("If set, version parameter will be interpreted as minimum required version within that minor/patch version.\n\
            It will return information about a version 'x' found among installed modules such that 'a.b <= x < a.(b+1)'.")
                .long("relaxed")
                .num_args(0)
                .required(false)
            )
        )
        .subcommand(clap::Command::new("sdk-info")
            .about("Returns information about an installed Nodos SDK under workspace.\n\
        If no such version is found, it will return an error.")
            .arg(Arg::new("version").required(true))
            .arg(Arg::new("sdk-type").required(false)
                .help("Type of the SDK to get information about.")
                .default_value("engine")
                .value_parser(clap::builder::PossibleValuesParser::new(["engine", "plugin", "subsystem", "process"])))
        )
        .subcommand(clap::Command::new("remote")
            .about("Manage remotes.")
            .subcommand(clap::Command::new("add")
                .about("Add a remote")
                .arg(Arg::new("url").required(true))
            )
            .subcommand(clap::Command::new("list")
                .about("List remotes")
            )
            .subcommand(clap::Command::new("remove")
                .about("Remove a remote")
                .arg(Arg::new("url").required(true))
            )
        )
        .subcommand(clap::Command::new("create")
            .about("Create a Nodos plugin or subsystem module")
            .arg(Arg::new("type")
                .value_parser(clap::builder::PossibleValuesParser::new(["plugin", "subsystem"]))
                .required(true)
            )
            .arg(Arg::new("name")
                .required(true)
            )
            .arg(lang_tool_arg.clone())
            .arg(Arg::new("output_dir")
                .help("Path to create the module folder in")
                .long("output-dir")
                .short('o')
                .default_value("./Module")
                .required(false)
            )
            .arg(Arg::new("prefix")
                .help("Folder path relative to out_dir. The module contents will be under this folder. By default, its '<module_name>'.")
                .long("prefix")
                .required(false)
            )
            .arg(Arg::new("yes_to_all")
                .action(ArgAction::SetTrue)
                .long("yes-to-all")
                .help("Do not ask for confirmation & use defaults for missing parameters")
                .num_args(0)
                .short('y')
                .required(false)
            )
            .arg(Arg::new("description")
                .help("Description of the module")
                .long("description")
                .default_value("")
                .required(false)
            )
            .arg(Arg::new("dependency")
                .help("Add module dependency. Can be specified multiple times. Format: <module_name>-<version>")
                .long("dependency")
                .short('d')
                .required(false)
                .action(ArgAction::Append)
                .num_args(1)
            )
        )
        .subcommand(clap::Command::new("get-sample")
            .alias("sample")
            .about("Get a sample plugin, subsystem or a process implementation for Nodos")
            .arg(Arg::new("name")
                .value_parser(clap::builder::PossibleValuesParser::new(sample::SAMPLES.keys().copied().collect::<Vec<&str>>().as_slice()))
                .required(true)
            )
            .arg(Arg::new("output_dir")
                .help("Path to bring the sample to")
                .long("output-dir")
                .short('o')
                .required(true)
            )
        )
        .subcommand(clap::Command::new("get").visible_alias("update")
            .about("Brings a Nodos release under workspace (with --workspace option).\n\
        If there is an existing Nodos release, updates it (note that this will remove all installed Nodos engines!)")
            .arg(Arg::new("name")
                .help("Name of the Nodos release to bring. Can be 'nodos' or some bundled version.")
                .long("name")
                .default_value("nodos")
            )
            .arg(Arg::new("version")
                .help("Version of the Nodos release to bring. If not provided, the latest version will be installed.")
                .long("version")
                .short('v')
                .required(false)
            )
            .arg(Arg::new("yes_to_all")
                .help("Do not ask for confirmation. Execute default behaviour.")
                .short('y')
                .action(ArgAction::SetTrue)
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("clean_modules")
                .help("Remove Nodos modules before installing the new release.")
                .action(ArgAction::SetTrue)
                .num_args(0)
                .required(false)
                .long("clean-modules")
            )
        )
        .subcommand(clap::Command::new("publish")
            .about("Publish a package")
            .after_help("This command will publish a package to the specified remote.\n\
        Currently, only the git repositories hosted on GitHub can be used to publish.")
            .arg(Arg::new("path")
                .long("path")
                .short('p')
                .help(format!("Path to the root folder of the package (or a file) to be published.\n\
            If not provided, the current directory will be used.\n\
            If the path is a folder and it does not contain a {} file, it will add all files to the release.", constants::PUBLISH_OPTIONS_FILE_NAME))
                .default_value(".")
            )
            .arg(Arg::new("name")
                .long("name")
                .short('n')
                .help("Name of the package. It will be overridden by the module manifest files under <path> if present.\n\
            If the <path> does not contain a module manifest file, this parameter is required."))
            .arg(Arg::new("version")
                .long("version")
                .help("Version of the package. It will be overridden by the module manifest files under <path> if present.\n\
            If the <path> does not contain a module manifest file, this parameter is required.")
            )
            .arg(Arg::new("version_suffix")
                .long("version-suffix")
                .help("Suffix to append to the version of the package.")
                .default_value("")
            )
            .arg(Arg::new("remote")
                .help("Name of the remote to publish to.")
                .long("remote")
                .default_value("default")
            )
            .arg(Arg::new("type")
                .long("type")
                .short('t')
                .value_parser(clap::builder::PossibleValuesParser::new(["plugin", "subsystem", "nodos", "engine", "generic"]))
                .help("Type of the package. It will be overridden by the module manifest files under <path> if present.\n\
            If the <path> does not contain a module manifest file, this parameter is required.")
            )
            .arg(Arg::new("vendor")
                .help("Who is publishing the package?\n\
            Required if the module to be published was not added to the index before.")
                .long("vendor")
            )
            .arg(Arg::new("publisher_name")
                .help("Git name of the publishing agent. If not provided, the name of the current git user will be used.")
                .long("publisher-name")
                .required(false)
            )
            .arg(Arg::new("publisher_email")
                .help("Git email of the publishing agent. If not provided, the email of the current git user will be used.")
                .long("publisher-email")
                .required(false)
            )
            .arg(Arg::new("dry_run")
                .action(ArgAction::SetTrue)
                .long("dry-run")
                .help("Do not actually publish the package, just show what would be done.")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("verbose")
                .action(ArgAction::SetTrue)
                .long("verbose")
                .help("Print more information about the process.")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("tag")
                .action(ArgAction::Append)
                .long("tag")
                .help("Add a tag to the release. Can be specified multiple times.")
                .required(false)
                .num_args(1)
            )
            .arg(Arg::new("target_platform")
                .long("target-platform")
                .help("Target architecture and operating system of the module to be published. If not provided, the current platform will be used.")
                .required(false)
            )
            .arg(version_check_arg.clone())
        )
        .subcommand(clap::Command::new("publish-batch")
            .about("Publish all/changed modules under the git repository.")
            .after_help(format!("This command will publish all/changed modules under the git repository to the specified remote.\n\
        It will use the {} files to compare file changes & adding files to the release. In the {} file, 'trigger_publish_globs' field will be used check file changes. \
        The 'release_globs' field however, will both be used for including files to the release as well as checking file changes.", constants::PUBLISH_OPTIONS_FILE_NAME, constants::PUBLISH_OPTIONS_FILE_NAME))
            .arg(Arg::new("remote")
                .help("Name of the remote to publish to.")
                .default_value("default")
            )
            .arg(Arg::new("repo_path")
                .long("repo-path")
                .short('r')
                .help("Path to the root folder of the repository. If not provided, the current directory will be used.")
                .default_value(".")
            )
            .arg(Arg::new("compare_with")
                .long("compare-with")
                .short('c')
                .help("Compare current with the given branch, tag or ref.\n\
            If not provided or empty, it will publish all modules found under the provided repo.")
            )
            .arg(Arg::new("version_suffix")
                .long("version-suffix")
                .help("Suffix to append to the version of the modules to be published.")
                .default_value("")
            )
            .arg(Arg::new("vendor")
                .help("Who is publishing the package?\n\
            Required if the module to be published was not added to the index before.")
                .long("vendor")
            )
            .arg(Arg::new("publisher_name")
                .help("Git name of the publishing agent. If not provided, the name of the current git user for the remote will be used.")
                .long("publisher-name")
                .required(false)
            )
            .arg(Arg::new("publisher_email")
                .help("Git email of the publishing agent. If not provided, the email of the current git user for the remote will be used.")
                .long("publisher-email")
                .required(false)
            )
            .arg(Arg::new("dry_run")
                .action(ArgAction::SetTrue)
                .long("dry-run")
                .help("Do not actually publish the package, just show what would be done.")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("verbose")
                .action(ArgAction::SetTrue)
                .long("verbose")
                .help("Print more information about the process.")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("tag")
                .action(ArgAction::Append)
                .long("tag")
                .help("Add a tag to the release. Can be specified multiple times.")
                .required(false)
                .num_args(1)
            )
            .arg(Arg::new("target_platform")
                .long("target-platform")
                .help("Target architecture and operating system of the module to be published. If not provided, the current platform will be used.")
                .required(false)
            )
            .arg(Arg::new("release_notes")
                .long("release-notes")
                .help("Release notes for the release.")
                .required(false)
            )
            .arg(version_check_arg)
        )
        .subcommand(clap::Command::new("unpublish")
            .alias("yank")
            .about("Unpublish a package from the index.")
            .arg(Arg::new("package_name").required(true))
            .arg(Arg::new("remote")
                .help("Name of the remote to edit.")
                .long("remote")
                .default_value("default")
            )
            .arg(Arg::new("version")
                .help("Version of the package to unpublish. If not provided, all versions will be unpublished."))
            .arg(Arg::new("dry_run")
                .action(ArgAction::SetTrue)
                .long("dry-run")
                .help("Do not actually publish the package, just show what would be done.")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("verbose")
                .action(ArgAction::SetTrue)
                .long("verbose")
                .help("Print more information about the process.")
                .num_args(0)
                .required(false)
            )
        )
        .subcommand(clap::Command::new("pin")
            .about("Add/remove a pin to/from a node definition")
            .arg(Arg::new("node_class_name")
                .required(true)
                .help("Node class name to add/remove pin.")
            )
            .arg(Arg::new("pin_name")
                .required(true)
                .help("Name of the pin to add/remove.")
            )
            .arg(Arg::new("remove")
                .action(ArgAction::SetTrue)
                .long("remove")
                .help("Remove the pin.")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("show_as")
                .long("show-as")
                .help("Determine whether the pin is input, property or output pin.")
                .value_parser(clap::builder::PossibleValuesParser::new(constants::POSSIBLE_SHOW_AS))
            )
            .arg(Arg::new("can_show_as")
                .long("can-show-as")
                .help("Determine the kind of the pin.")
                .required(false)
                .value_parser(clap::builder::PossibleValuesParser::new(constants::POSSIBLE_CAN_SHOW_AS))
            )
            .arg(Arg::new("type_name")
                .long("type-name")
                .help("Data type name of the pin")
                .required(false)
            )
        )
        .subcommand(clap::Command::new("node")
            .about("Add/remove a node definition in a Nodos plugin")
            .arg(Arg::new("plugin")
                .required(true)
                .help("Name of the plugin to add/remove a node.")
            )
            .arg(Arg::new("node_class_name")
                .required(true)
                .help("Node class name to add/remove.")
            )
            .arg(Arg::new("remove")
                .action(ArgAction::SetTrue)
                .long("remove")
                .help("Remove the node class.")
                .num_args(0)
                .required(false)
            )
            .arg(Arg::new("display_name")
                .long("display-name")
                .help("Display name of the node class.")
                .required(false)
            )
            .arg(Arg::new("description")
                .long("description")
                .help("Description of the node class.")
                .required(false)
            )
            .arg(Arg::new("category")
                .long("category")
                .help("Category of the node class.")
                .required(false)
            )
            .arg(Arg::new("hide_in_context_menu")
                .action(ArgAction::SetTrue)
                .long("hide")
                .help("Should Nodos editors hide it in the editor context menu?")
                .required(false)
                .num_args(0)
            )
        )
        .subcommand(clap::Command::new("depend")
            .about("Add dependency to a Nodos module")
            .arg(Arg::new("module")
                .required(true)
                .help("Name of the module to add a dependency to.")
            )
            .arg(Arg::new("dependency")
                .help("Dependency to be added. Can be specified multiple times. Version is not required. Format: <module_name>-<version>")
                .required(false)
                .action(ArgAction::Append)
                .num_args(1..)
            )
        )
        .subcommand(clap::Command::new("launch")
            .about("Launch Nodos")
        )
        .subcommand(clap::Command::new("dev")
            .about("Helper commands for Nodos module development")
            .subcommand(clap::Command::new("pull")
                .about("Scans for git repositories and pulls their current branches")
                .arg(git_dir_arg.clone())
            )
            .subcommand(clap::Command::new("gen")
                .about("Generates project files for Nodos module development")
                .arg(lang_tool_arg.clone())
                .arg(Arg::new("project_folder")
                    .long("project-folder")
                    .short('p')
                    .help("Path to the project folder to generate files in")
                    .default_value("Project"))
                .arg(Arg::new("extra_args")
                    .last(true)
                    .help("Arguments to pass to the underlying tool when generating project files")
                )
            )
            .subcommand(clap::Command::new("build")
                .about("Builds project files for Nodos module development")
                .arg(lang_tool_arg)
                .arg(Arg::new("project_folder")
                    .long("project-folder")
                    .short('p')
                    .help("Path to the project folder to build")
                    .default_value("Project"))
                .arg(Arg::new("extra_args")
                    .last(true)
                    .help("Arguments to pass to the underlying tool when building project files")
                )
            )
            .subcommand(clap::Command::new("status")
                .about("Shows the status of the git repositories under the workspace")
                .arg(git_dir_arg)
            )
        )
        .subcommand(clap::Command::new("test")
            .about("Enumerate modules in a folder, look under Tests folder of each module, and run nosLauncher with --load-graph for each graph file.")
            .arg(clap::Arg::new("modules_folder")
                .help("Path to the folder containing modules (default: workspace root)")
                .long("modules-folder")
                .short('m')
                .required(false)
            )
            .arg(clap::Arg::new("engine_dir")
                .help("Path to the engine directory to use for nosLauncher (default: auto-detect from workspace)")
                .long("engine-dir")
                .short('e')
                .required(false)
            )
            .arg(clap::Arg::new("timeout")
                .help("Timeout in seconds for each test")
                .long("timeout")
                .short('t')
                .required(false)
                .value_parser(clap::value_parser!(u64))
                .default_value("30")
            )
        )
}