# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    branches:
      - "dev"        # Specific branch
      - "[0-9]+.[0-9]+" # Version branches
    paths:
      - "Toolchain/nosman/**" # Only run when files in this directory are changed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      clean:
        type: boolean
        description: 'Clean build'
        required: true
      sign:
        type: boolean
        description: 'Sign binaries'
        required: true
      linux:
        description: 'Release for Linux'
        required: true
        default: true
        type: boolean
      windows:
        description: 'Release for Windows'
        required: true
        default: true
        type: boolean

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GH_USERNAME: "nodos-bot"
  GIT_EMAIL: "bot@nodos.dev"

# TODO: Support parallel runs
concurrency:
  group: ${{ github.ref_name }} # For now, allow 1 run at a time for each branch
  cancel-in-progress: false # Queue up runs if one is already in progress.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare-strategy:
    name: Prepare Strategy
    runs-on: self-hosted
    outputs:
      runner-list: ${{ steps.prepare-step.outputs.runner-list }}
    steps:
      - name: Prepare Runner List
        id: prepare-step
        shell: bash
        run: |
          runner_list=$(python3 -c "$(wget -q -O - https://raw.githubusercontent.com/nodos-dev/actions/refs/heads/main/scripts/prep_runner_list.py)" \
            --workflow-input-linux ${{ inputs.linux }} \
            --workflow-input-windows ${{ inputs.windows }} \
            --sign ${{ inputs.sign }} \
            --ref-name ${{ github.ref_name }} \
            --event-name ${{ github.event_name }} \
            --push-event-defaults '{"linux": true, "windows": true, "sign": false}')
          echo Runners: $runner_list
          echo "runner-list=$runner_list" >> $GITHUB_OUTPUT

  build_nosman:
    strategy:
      matrix:
        runner: ${{ fromJson(needs.prepare-strategy.outputs.runner-list) }}
      fail-fast: false
    name: "Nosman: ${{ github.ref_name }} - ${{ github.run_number }} (${{ matrix.runner[0] }})"
    runs-on: ${{ matrix.runner }}
    needs: prepare-strategy
    steps:
      - name: Update Git Credentials
        shell: bash
        run: |
            if [ "${{ matrix.runner[0] }}" == "Linux" ]; then
            export GPG_TTY=$(tty)
            fi
            git credential-manager github login --username ${{ env.GH_USERNAME }} --token ${{ secrets.CI_TOKEN }} --force

      - name: Clean Build
        shell: pwsh
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.clean == 'true' }}
        run: |
            if (Test-Path -Path ./nodos-workspace-${{ github.ref_name }}) { Remove-Item -Path ./nodos-workspace-${{ github.ref_name }} -Recurse -Force }

      - name: Checkout Nodos Workspace
        shell: pwsh
        run: |
            $ErrorActionPreference = 'Stop'
            if (-not (Test-Path -Path ./nodos-workspace-${{ github.ref_name }})) {
            git clone --depth 1 https://github.com/${{ github.repository }}.git --recurse-submodule --shallow-submodules ./nodos-workspace-${{ github.ref_name }}
            }
            cd ./nodos-workspace-${{ github.ref_name }}
            git fetch origin
            git clean -ffd
            git checkout .
            git checkout dev
            git clean -ffd
            git restore .
            git pull
            git submodule update --force --recursive --init
            git status

      - name: Build Nosman
        shell: pwsh
        run: |
            cargo build --release
        working-directory: ./nodos-workspace-${{ github.ref_name }}/Toolchain/nosman

      - name: Run Regression Tests
        shell: pwsh
        run: |
            cargo test --release
        working-directory: ./nodos-workspace-${{ github.ref_name }}/Toolchain/nosman

      - name: Get Version
        shell: pwsh
        id: get-version
        # Get version from built binary --version. Strip the output to get the version numbers only.
        run: |
            $ErrorActionPreference = 'Stop'
            $version = & ./nosman --version | Out-String
            $version = $version -replace '.*?(\d+\.\d+\.\d+).*', '$1'
            echo "Version: $version"
            echo "version=$version" >> $GITHUB_OUTPUT
        working-directory: ./nodos-workspace-${{ github.ref_name }}/Toolchain/nosman/target/release

      - name: Sign Binaries
        if: ${{ matrix.runner[0] == 'Windows' && inputs.sign == 'true' }}
        run: |
          cd $MEDIAZ_SCRIPTS_DIR
          python sign_module.py "${{ github.workspace }}/nodos-workspace-${{ github.ref_name }}/Toolchain/nosman/target/release"
        shell: bash

      - name: Create GitHub Release
        shell: pwsh
        id: create-release
        run: |
          $ErrorActionPreference = 'Stop'
          $platform = if (${{ matrix.runner[0] }} -eq 'Windows') { 'windows' } else { 'linux' }
          $file = if (${{ matrix.runner[0] }} -eq 'Windows') { './nosman.exe' } else { './nosman' }
          $renamed_file = "./nosman-$platform"
          Rename-Item -Path $file -NewName $renamed_file
          # Check if the release already exists
          $release_exists = gh release view v${{ steps.get-version.outputs.version }} > $null 2>&1
          if (-not $release_exists) {
              gh release create v${{ steps.get-version.outputs.version }} $renamed_file --title "Release v${{ steps.get-version.outputs.version }}" --generate-notes
          } else {
              gh release upload v${{ steps.get-version.outputs.version }} $renamed_file --clobber
          }
        working-directory: ./nodos-workspace-${{ github.ref_name }}/Toolchain/nosman/target/release

      - name: Publish Nosman to Nodos index
        if: ${{ matrix.runner[0] == 'Linux' || matrix.runner[0] == 'Windows' }}
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $file = if (${{ matrix.runner[0] }} -eq 'Windows') { './nosman.exe' } else { './nosman' }
          ./nosman publish --path $file --name "nosman" --version ${{ steps.get-version.outputs.version }} --type generic --vendor "Nodos" --verbose
        working-directory: ./nodos-workspace-${{ github.ref_name }}/Toolchain/nosman/target/release